### PR TITLE
Profile Page

### PR DESCRIPTION
**Pull request by DarkTXYZ**

### CODE REVIEW

**Review by iambaangkok — COMMENTED** [review]
Waiting for tests.

**Comment by iambaangkok** [comment]
@DarkTXYZ 
Wrote all the necessary/testable tests.
Also pulled from `origin master` to this branch and resolved all merge conflicts.

There is **1 failed test**. If that is fixed then the this PR should be finished.

**Review by iambaangkok — CHANGES_REQUESTED** [review]
Request the title of the profile page to include "Profile" somewhere in the string.

**Comment by DarkTXYZ** [comment]
@iambaangkok 
The Profile page title has been added.

**Review by iambaangkok — APPROVED** [review]

**Pull request merged**
